name: Build Mustache & Stylus

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '15'
      - name: Copy resources
        run: |-
          mkdir -p build/static

          cp *.html build/ || :
          cp -R static/ build/ || :
      - name: Set up Stylus
        run: |-
          sudo apt install node-stylus
      - name: Invoke Stylus
        run: |-
          mkdir -p build/static/css
          stylus -c stylus -o build/static/css
      - name: Set up Kotlin
        run: |-
          sudo snap install --classic kotlin
      - name: Invoke Mustache
        run: |-
          kotlinVersion='1.4.30'
          kmsUrl="https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-main-kts/$kotlinVersion/kotlin-main-kts-$kotlinVersion.jar"
          kmsBasename=$(basename $kmsUrl)
          wget -nc $kmsUrl
          echo "Using kotlin-main-kts artifact $kmsBasename ($kotlinVersion)"

          kotlinc -cp $kmsBasename -script site.main.kts
      - name: Deploy to master
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: build/
          CLEAN: true
          COMMIT_MESSAGE: Deployed from develop
